[package]
name = "triple_accel"
version = "0.1.0"
authors = ["c0deb0t <daniel.liu02@gmail.com>"]
edition = "2018"

[[bench]]
name = "rand_benchmarks"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.3"
rand = "0.7.3"

