name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests AVX2/8-bit
      run: cargo test --verbose --no-default-features --features "debug jewel-avx jewel-8bit" -- --nocapture
    - name: Run bench tests AVX2/8-bit
      run: cargo test --bench rand_benchmarks --verbose --no-default-features --features "debug jewel-avx jewel-8bit" -- --nocapture
    - name: Run tests AVX2/16-bit
      run: cargo test --verbose --no-default-features --features "debug jewel-avx jewel-16bit" -- --nocapture
    - name: Run bench tests AVX2/16-bit
      run: cargo test --bench rand_benchmarks --verbose --no-default-features --features "debug jewel-avx jewel-16bit" -- --nocapture
    - name: Run tests AVX2/32-bit
      run: cargo test --verbose --no-default-features --features "debug jewel-avx jewel-32bit" -- --nocapture
    - name: Run bench tests AVX2/32-bit
      run: cargo test --bench rand_benchmarks --verbose --no-default-features --features "debug jewel-avx jewel-32bit" -- --nocapture
    - name: Run tests SSE4.1/8-bit
      run: cargo test --verbose --no-default-features --features "debug jewel-sse jewel-8bit" -- --nocapture
    - name: Run bench tests SSE4.1/8-bit
      run: cargo test --bench rand_benchmarks --verbose --no-default-features --features "debug jewel-sse jewel-8bit" -- --nocapture
    - name: Run tests SSE4.1/16-bit
      run: cargo test --verbose --no-default-features --features "debug jewel-sse jewel-16bit" -- --nocapture
    - name: Run bench tests SSE4.1/16-bit
      run: cargo test --bench rand_benchmarks --verbose --no-default-features --features "debug jewel-sse jewel-16bit" -- --nocapture
    - name: Run tests SSE4.1/32-bit
      run: cargo test --verbose --no-default-features --features "debug jewel-sse jewel-32bit" -- --nocapture
    - name: Run bench tests SSE4.1/32-bit
      run: cargo test --bench rand_benchmarks --verbose --no-default-features --features "debug jewel-sse jewel-32bit" -- --nocapture
